source 'https://rubygems.org'

gem 'rails'
gem 'pg'
gem 'bootstrap-sass'
gem 'sprockets'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'bcrypt-ruby'
gem 'jquery-rails'
gem 'turbolinks'
gem 'devise'
gem 'autoprefixer-rails'
gem 'paperclip'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'quiet_assets'
end

group :test, :development do
  gem 'rspec-rails'
end

group :test do
  gem 'shoulda-matchers'
end

group :production do
  gem 'rails_12factor'
end
